# Generated by Django 3.1.7 on 2021-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('hospitalID', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('hospitalName', models.TextField(max_length=30)),
                ('hospitalAddress', models.TextField(max_length=50)),
            ],
        ),
    ]
