# Generated by Django 3.1.7 on 2021-03-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensorID', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('sensorName', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('patientID', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('patientName', models.TextField(max_length=30)),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.hospitaldata')),
            ],
        ),
        migrations.CreateModel(
            name='ECGData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.FloatField()),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.patientdata')),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitor.sensordata')),
            ],
        ),
    ]
